#pragma once

#include "snobol/c23_compat.h"

#ifdef __cplusplus
extern "C" {
#endif


/**
 * @file snobol.h
 * @brief Main API entry point for libsnobol4
 *
 * libsnobol4 is a high-performance C library implementing SNOBOL4-style
 * pattern matching. This header provides the main API entry point,
 * re-exporting common types and functions for convenient single-include usage.
 *
 * ## Reusable Match API
 *
 * For hot loops (e.g. searchSplit with 1000+ matches), use:
 * - snobol_match_create(): allocate a reusable match object
 * - snobol_pattern_search_reuse(): search using a caller-allocated match object
 * - snobol_match_reset(): clear match state between reuse cycles
 * - snobol_match_free(): release the match object
 *
 * This eliminates per-call malloc/free overhead (~30 ns per match).
 *
 * @version 0.13.0
 */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* -----------------------------------------------------------------------
 * Version macros
 *
 * SNOBOL_VERSION_* and SNOBOL_VERSION_STRING are generated by CMake into
 * `snobol/version.h` from the single source of truth in the top-level
 * `project(libsnobol4 VERSION X.Y.Z)` declaration.  They are NOT hard-coded
 * here; to bump the version, edit CMakeLists.txt and reconfigure.
 * ----------------------------------------------------------------------- */
#include "snobol/version.h"

/** @brief ABI version number (monotonically increasing).
 *
 *  Incremented on any breaking ABI change.  The initial value is 1.
 *  Bindings can check this at load time to detect incompatibility. */
#define SNOBOL_ABI_VERSION 1

/* -----------------------------------------------------------------------
 * Deprecation macros
 *
 * Use SNOBOL_DEPRECATED to mark public API functions that are deprecated
 * but kept for one minor version cycle before removal.  Deprecated
 * functions produce a compiler warning.
 *
 *   SNOBOL_DEPRECATED void snobol_old_func(void);
 * ----------------------------------------------------------------------- */
#if defined(__GNUC__) || defined(__clang__)
#define SNOBOL_DEPRECATED __attribute__((deprecated))
#elif defined(_MSC_VER)
#define SNOBOL_DEPRECATED __declspec(deprecated)
#else
#define SNOBOL_DEPRECATED
#endif

/**
 * Get library version at runtime (three separate integers)
 * @param major Output parameter for major version (can be NULL)
 * @param minor Output parameter for minor version (can be NULL)
 * @param patch Output parameter for patch version (can be NULL)
 */
void snobol_version(int *major, int *minor, int *patch);

/**
 * Get library API version as a single encoded integer.
 *
 * Encoding: (MAJOR << 16) | (MINOR << 8) | PATCH
 *
 * Bindings should compare `snobol_get_api_version() >> 16` against their
 * compile-time SNOBOL_VERSION_MAJOR to detect incompatible library upgrades.
 *
 * @return Encoded API version uint32_t.
 *         For v0.11.0 this returns 0x00000B00u.
 */
uint32_t snobol_get_api_version(void);

/**
 * Get the ABI version of the library.
 *
 * Returns a monotonically-increasing integer that is bumped whenever a
 * breaking change is made to the public ABI.  Bindings and dynamic
 * loaders can call this at initialisation to verify compatibility.
 *
 * The initial v0.11.0 value is 1.
 *
 * @return ABI version integer.
 */
uint32_t snobol_get_abi_version(void);

/* Include common headers */
#include "snobol/array.h"
#include "snobol/ast.h"
#include "snobol/compiler.h"
#include "snobol/dynamic_pattern.h"
#include "snobol/lexer.h"
#include "snobol/parser.h"
#include "snobol/search.h"
#include "snobol/string_fn.h"
#include "snobol/table.h"
#include "snobol/type_fn.h"
#include "snobol/vm.h"

/**
 * @brief Pattern matching context (opaque handle)
 *
 * The context owns all compiled patterns and associated resources.
 * Create with snobol_context_create(), destroy with snobol_context_destroy().
 */
typedef struct snobol_context snobol_context_t;

/**
 * @brief Compiled pattern (opaque handle)
 *
 * Represents a compiled pattern ready for matching.
 * Created via snobol_pattern_compile().
 */
typedef struct snobol_pattern snobol_pattern_t;

/**
 * @brief Maximum named variables returned from a match.
 */
#define SNOBOL_API_MAX_VARS 64

/**
 * @brief Result from snobol_pattern_search_batch().
 *
 * Contains all non-overlapping matches found in a single pass, stored as
 * flat C arrays.  All array memory is allocated with snobol_malloc; the
 * caller must free via snobol_batch_result_free().
 *
 * When no captures are present, var_count is 0 and captures is NULL.
 * outputs is NULL when no match produced EMIT output.  Each output segment
 * is NUL-terminated; the final segment is followed by an empty-string sentinel
 * so callers can iterate outputs without needing output_lens.
 *
 * eligible distinguishes "no matches but the pattern was batch-eligible"
 * (true, zero matches) from "the pattern was not batch-eligible" (false).
 * Callers must check eligible: a false return with eligible == true means the
 * search completed with zero matches (DONE) — do NOT re-run the search.  A
 * false return with eligible == false means the pattern must fall back to the
 * per-call loop.  eligible is set true for every batch-eligible pattern
 * regardless of match count, and false (the safe default) for early-outs.
 */
typedef struct snobol_batch_result {
  size_t match_count;  /**< Number of matches found (0 when return false). */
  size_t *positions;   /**< [match_count] match start offsets. */
  size_t *lengths;     /**< [match_count] match byte lengths. */
  size_t var_count;    /**< Number of capture registers (0 = no captures). */
  size_t **captures;   /**< [var_count][match_count * 2]: each row stores
                                 [start0, len0, start1, len1, ...]. */
  char *outputs;       /**< Concatenated NUL-terminated output strings,
                                 one per match, final sentinel is empty. */
  size_t *output_lens; /**< [match_count] byte length of each output. */
  bool eligible;       /**< True when the pattern was batch-eligible
                                 (zero matches still sets this). */
} snobol_batch_result_t;

/**
 * @brief Find all non-overlapping matches in a single pass.
 *
 * Runs the search engine's main loop once, collecting every match's
 * position, length, captures, and EMIT output into flat arrays in a
 * single result struct.  The caller must free the result arrays with
 * snobol_batch_result_free().
 *
 * Patterns with side-effect ops (EVAL, ASSIGN, DYNAMIC) are not supported
 * and return false immediately (out->eligible == false; caller falls back to
 * the per-call loop).
 *
 * For batch-eligible patterns the search runs once and out->eligible is set
 * true.  When zero matches are found the function returns false but
 * out->eligible stays true — the caller must treat that as DONE (no fallback),
 * not as a request to re-run the search via the per-call loop.
 *
 * @param bc       Compiled bytecode buffer (must outlive the call).
 * @param bc_len   Bytecode length.
 * @param subject  Subject string (must outlive the call — captures reference
 *                 offsets into it).
 * @param len      Subject byte length.
 * @param meta     Pre-derived search metadata (from snobol_search_derive_meta
 *                 or snobol_pattern_get_meta()).
 * @param out      Output struct (caller-allocated, zero-initialised).
 * @return true when at least one match was found; false otherwise.
 *         On false, out->match_count is 0 and all arrays are NULL (or empty
 *         for ineligible patterns).  Check out->eligible to tell zero-match
 *         (eligible == true, DONE) from ineligible (eligible == false, fall
 *         back to per-call loop).
 */
bool snobol_pattern_search_batch(const uint8_t *bc, size_t bc_len,
                                 const char *subject, size_t len,
                                 const snobol_search_meta_t *meta,
                                 snobol_batch_result_t *out);

/**
 * @brief Free all arrays owned by a batch result struct.  NULL-safe.
 *
 * Releases positions, lengths, captures, outputs, and output_lens arrays.
 * Does NOT free the struct itself (caller-allocated).
 */
void snobol_batch_result_free(snobol_batch_result_t *out);

/**
 * @brief Match result object.
 *
 * Contains the result of a successful pattern match,
 * including captured variables and output buffer.
 * Use snobol_match_create() to allocate, snobol_match_free() to release.
 */
typedef struct snobol_match {
  bool success;

  /* Output buffer (from OP_EMIT_* instructions) */
  char *output;
  size_t output_len;

  /* Named capture variables.
   *
   * Captures are stored register-style as (offset, length) pairs relative to
   * `var_subject` (var_off[i], var_len[i]).  The NUL-terminated byte copy in
   * var_values[i] is materialized lazily on the first snobol_match_get_variable
   * call and cached there; a NULL var_values[i] with var_len[i] > 0 means the
   * capture is present but not yet copied.  This avoids a per-match malloc +
   * memcpy for every variable when the caller only reads a subset (or none).
   *
   * Variable names are decimal strings "1", "2", …, "64".
   * Index 0 corresponds to variable name "1" (1-based). */
  const char *var_subject;
  size_t var_off[SNOBOL_API_MAX_VARS];
  size_t var_len[SNOBOL_API_MAX_VARS];
  char *var_values[SNOBOL_API_MAX_VARS];
  size_t var_lens[SNOBOL_API_MAX_VARS];
  int var_count;

  /* Match position within the subject. */
  size_t position;
  size_t length;
} snobol_match_t;

/**
 * @brief Associative table (opaque handle)
 *
 * Runtime-owned string-keyed hash table for table-backed substitutions.
 */
typedef struct snobol_table snobol_table_t;

typedef struct snobol_array snobol_array_t;

/* Context lifecycle */
/**
 * @brief Create a new pattern matching context.
 *
 * The context owns all compiled patterns and associated resources.
 * Must be destroyed with snobol_context_destroy() when no longer needed.
 *
 * @return New context, or NULL on allocation failure.
 */
snobol_context_t *snobol_context_create(void);

/**
 * @brief Destroy a pattern matching context and free all associated resources.
 *
 * All patterns compiled under this context are invalidated.
 * Passing NULL is safe (no-op).
 *
 * @param[in] ctx Context to destroy.
 */
void snobol_context_destroy(snobol_context_t *ctx);

/* -----------------------------------------------------------------------
 * Pattern compilation flags
 * ----------------------------------------------------------------------- */

/**
 * Make literal and character-class matching case-insensitive for ASCII and
 * Latin-1 Supplement (U+0041–U+005A / U+0061–U+007A; U+00C0–U+00FF pairs).
 * Captured text preserves the original subject case.
 *
 * Pass to snobol_pattern_compile_ex() via the flags bitmask.
 */
#define SNOBOL_FLAG_CASE_INSENSITIVE 0x0001u

/* Pattern compilation */
/**
 * @brief Compile a SNOBOL4 pattern string to a compiled pattern object.
 *
 * Equivalent to snobol_pattern_compile_ex() with @p flags = 0.
 *
 * @param[in]  ctx    Context that will own the returned pattern.
 * @param[in]  source Pattern source text (UTF-8).
 * @param[in]  len    Byte length of @p source.
 * @param[out] error  On failure, *error is set to a malloc'd error string that
 *                    the caller must free.  Set to NULL on success.
 * @return Compiled pattern owned by @p ctx, or NULL on parse/compile error.
 *         Free with snobol_pattern_free() before destroying the context.
 */
snobol_pattern_t *snobol_pattern_compile(snobol_context_t *ctx,
                                         const char *source, size_t len,
                                         char **error);

/**
 * Compile a pattern with option flags.
 *
 * @param ctx    Context that owns the returned pattern.
 * @param source Pattern source text (UTF-8).
 * @param len    Byte length of source.
 * @param flags  Bitmask of SNOBOL_FLAG_* constants (unknown bits are ignored).
 * @param error  On failure, *error is set to a malloc'd error string.
 *               On success, *error is set to NULL.  Caller must free on error.
 * @return Compiled pattern owned by ctx, or NULL on parse/compile error.
 *         Free with snobol_pattern_free() before destroying the context.
 */
snobol_pattern_t *snobol_pattern_compile_ex(snobol_context_t *ctx,
                                            const char *source, size_t len,
                                            uint32_t flags, char **error);

/**
 * @brief Get the bytecode pointer from a compiled pattern.
 * @param[in] pattern Compiled pattern.
 * @return Read-only pointer to the bytecode, or NULL if pattern is NULL.
 */
const uint8_t *snobol_pattern_get_bc(const snobol_pattern_t *pattern);

/**
 * @brief Get the bytecode length from a compiled pattern.
 * @param[in] pattern Compiled pattern.
 * @return Byte length, or 0 if pattern is NULL.
 */
size_t snobol_pattern_get_bc_len(const snobol_pattern_t *pattern);

/**
 * @brief Get the pre-derived search metadata for a compiled pattern.
 *
 * The metadata is computed once at compile time and reused by the search
 * runtime.  Exposed read-only for introspection and testing.
 *
 * @param[in] pattern Compiled pattern.
 * @return Read-only pointer to the search metadata, or NULL if pattern is NULL.
 */
const snobol_search_meta_t *snobol_pattern_get_meta(
    const snobol_pattern_t *pattern);

/**
 * @brief Retrieve cached charclass range metadata from a compiled pattern.
 *
 * The range metadata is built once at compile time and used by SPAN/BREAK/BREAKX
 * opcodes to resolve character-class set IDs.  Callers that invoke
 * snobol_search_exec() directly (bypassing snobol_pattern_search()) must
 * copy this into the VM's range_meta / range_meta_count fields.
 *
 * @param[in] pattern  Compiled pattern (NULL returns NULL/0).
 * @param[out] count   Number of entries in the returned array (may be NULL).
 * @return Read-only pointer to range metadata array, or NULL.
 */
const snobol_range_meta_t *snobol_pattern_get_range_meta(
    const snobol_pattern_t *pattern, size_t *count);

/**
 * @brief Free a compiled pattern.
 *
 * @param[in] pattern Pattern to free.  NULL is safe.
 */
void snobol_pattern_free(snobol_pattern_t *pattern);

/* Pattern matching */
/**
 * @brief Execute a compiled pattern against a subject string.
 *
 * @param[in] pattern Compiled pattern to execute.
 * @param[in] subject Subject string (UTF-8).
 * @param[in] len     Byte length of @p subject.
 * @return New match result that the caller must free with snobol_match_free().
 *         Always returns a valid pointer; call snobol_match_success() to
 *         determine whether the match succeeded.
 */
snobol_match_t *snobol_pattern_match(snobol_pattern_t *pattern,
                                     const char *subject, size_t len);

/**
 * @brief Lightweight result from snobol_pattern_match_literal().
 *
 * Zero heap allocations — returned by value.  Only valid for patterns
 * whose bytecode is a single anchored literal (e.g. "'abc'").
 */
typedef struct snobol_literal_match {
  bool success;    /**< Whether the literal matched at position 0. */
  size_t position; /**< Match start position (always 0 on success). */
  size_t length;   /**< Byte length of the matched literal. */
} snobol_literal_match_t;

/**
 * @brief Lightweight anchored literal match for literal-only patterns.
 *
 * If the compiled pattern's bytecode is a single anchored literal (e.g.
 * @c "'abc'"), this function performs a @c memcmp at position 0 with
 * zero heap allocations.  No VM setup, emit buffer, or capture tracking
 * is performed — the result is returned by value.
 *
 * For non-literal patterns or when the subject does not start with the
 * pattern literal, @c success is set to @c false.
 *
 * @param[in] pattern Compiled pattern to execute.
 * @param[in] subject Subject string (UTF-8).
 * @param[in] len     Byte length of @p subject.
 * @return Lightweight result struct (zero heap allocations).
 */
snobol_literal_match_t snobol_pattern_match_literal(snobol_pattern_t *pattern,
                                                    const char *subject,
                                                    size_t len);

/**
 * @brief Execute a compiled pattern in search (un-anchored) mode.
 *
 * Uses the search tier dispatch (memchr/memmem/bitmap fast paths) before
 * falling back to the interpreter VM when no tier matches. Finds the
 * first occurrence of the pattern anywhere in the subject string (like
 * SNOBOL4's @c ? or @c POS(0) match).
 *
 * @param[in] pattern Compiled pattern to execute.
 * @param[in] subject Subject string (UTF-8).
 * @param[in] len Byte length of @p subject.
 * @return New match result that the caller must free with snobol_match_free().
 *         Always returns a valid pointer; call snobol_match_success() to
 *         determine whether the match succeeded.
 */
snobol_match_t *snobol_pattern_search(snobol_pattern_t *pattern,
                                      const char *subject, size_t len);

/**
 * @brief Opaque state for snobol_pattern_search_ex().
 *
 * Holds the cached search metadata, a reusable VM, an output buffer,
 * and a reusable match result.  Created once per pattern, reused across
 * all matches in a search loop (e.g. PHP Pattern::searchSplit) to
 * avoid per-call allocation churn.
 *
 * Pointer ownership: created by snobol_pattern_search_state_create(),
 * destroyed by snobol_pattern_search_state_destroy(). The state holds
 * a reference to the pattern but does not own it; the caller must keep
 * the pattern alive until the state is destroyed.
 */
typedef struct snobol_pattern_search_state snobol_pattern_search_state_t;

/**
 * @brief Create a state object for snobol_pattern_search_ex().
 *
 * @param[in] bc     Compiled bytecode buffer. Must outlive the state.
 * @param[in] bc_len Byte length of @p bc.
 * @return Newly allocated state, or NULL on allocation failure.
 *         Free with snobol_pattern_search_state_destroy().
 */
snobol_pattern_search_state_t *snobol_pattern_search_state_create(
    const uint8_t *bc, size_t bc_len);

/**
 * @brief Associate an owning pattern with a search state.
 *
 * When set, repeated calls to snobol_pattern_search_ex() on the state reuse
 * the pattern's cached Tier-5 alternation trie instead of rebuilding it each
 * call. The pattern must outlive the state. Optional — callers that build a
 * state directly from bytecode (without a pattern object) need not call this.
 *
 * @param[in] state   State created by snobol_pattern_search_state_create().
 * @param[in] pattern Owning pattern (may be NULL to clear the association).
 */
void snobol_pattern_search_state_set_pattern(
    snobol_pattern_search_state_t *state, snobol_pattern_t *pattern);

/**
 * Set a pre-built alt-literals trie on the search state's VM.
 *
 * The trie is used by the Tier 5 alt-literals dispatch instead of
 * rebuilding it on every search call.  The caller owns the trie and
 * must keep it alive until the state is destroyed (the state does
 * not take ownership).
 *
 * @param[in] state  Search state created by snobol_pattern_search_state_create().
 * @param[in] trie   Pre-built trie, or NULL to clear.
 */
void snobol_pattern_search_state_set_trie_cache(
    snobol_pattern_search_state_t *state, snobol_auto_trie_t *trie);

/**
 * @brief Set the EVAL callback function on a search state's persistent VM.
 *
 * Once set, the callback persists for the lifetime of the state, avoiding
 * per-call allocation.  Pass NULL (the default) to clear.
 *
 * @param[in] state        Search state created by
 *                         snobol_pattern_search_state_create().
 * @param[in] eval_fn      EVAL callback (NULL to clear).
 * @param[in] eval_udata   Opaque pointer passed to @p eval_fn.
 */
void snobol_pattern_search_state_set_eval_fn(
    snobol_pattern_search_state_t *state,
    bool (*eval_fn)(int fn_id, const char *s, size_t start, size_t end,
                    void *userdata),
    void *eval_udata);

/**
 * @brief Destroy a search state object. NULL-safe.
 *
 * Releases the cached VM, output buffer, match result, and the
 * reference to the pattern's bytecode. Does NOT free the pattern
 * itself.
 */
void snobol_pattern_search_state_destroy(snobol_pattern_search_state_t *state);

/**
 * @brief Stateful search that reuses VM, output buffer, and match result
 * across calls.
 *
 * Functionally equivalent to repeated calls to
 * snobol_pattern_search() but amortises the per-call allocation cost.
 * Intended for hot loops (e.g. PHP Pattern::searchSplit, which performs
 * 1000+ matches per call).
 *
 * @param[in,out] state       Search state created by
 *                            snobol_pattern_search_state_create(). The
 *                            state's internal match result is
 *                            overwritten on each call.
 * @param[in]     subject     Subject string (UTF-8).
 * @param[in]     subject_len Byte length of @p subject.
 * @param[in]     start_offset Byte offset to start searching from
 *                            (0 = beginning).
 * @return Pointer to the internal match result owned by @p state, valid
 *         until the next call on the same state or state destruction.
 *         The caller must NOT free this pointer.
 */
snobol_match_t *snobol_pattern_search_ex(snobol_pattern_search_state_t *state,
                                         const char *subject,
                                         size_t subject_len,
                                         size_t start_offset);

/**
 * @brief Stateful anchored search that reuses VM, DFA, and range_meta.
 *
 * Identical to snobol_pattern_search_ex() but calls
 * snobol_search_exec_anchored() internally so the match MUST start at
 * offset 0 (SNOBOL-style anchored match).  Intended for Pattern::match().
 *
 * @param[in,out] state       Search state created by
 *                            snobol_pattern_search_state_create().
 * @param[in]     subject     Subject string (UTF-8).
 * @param[in]     subject_len Byte length of @p subject.
 * @return Pointer to the internal match result owned by @p state, valid
 *         until the next call on the same state or state destruction.
 *         The caller must NOT free this pointer.
 */
snobol_match_t *snobol_pattern_search_ex_anchored(
    snobol_pattern_search_state_t *state, const char *subject,
    size_t subject_len);

/**
 * @brief Lightweight unanchored search for single-literal patterns.
 *
 * Returns the position and length of the next occurrence of the pattern's
 * literal at or after @p start_offset, without the overhead of
 * snobol_pattern_search_ex() (no match struct, no capture arrays, no output
 * buffer).  Returns false for non-literal patterns — the caller must fall
 * back to snobol_pattern_search_ex().
 *
 * Per-call cost is ~15 ns (vs ~91 ns for snobol_pattern_search_ex with the
 * short-circuit, or ~158 ns for the full tier-dispatch path).
 *
 * @param[in]     state         Search state created by
 *                              snobol_pattern_search_state_create().
 * @param[in]     subject       Subject string.
 * @param[in]     subject_len   Byte length of @p subject.
 * @param[in]     start_offset  Start searching from this offset.
 * @param[out]    out_pos       Match start position (absolute in subject).
 * @param[out]    out_len       Match length (literal length).
 * @return true if a match was found, false otherwise (including when the
 *         pattern is not a single literal).
 */
bool snobol_pattern_search_next(snobol_pattern_search_state_t *state,
                                const char *subject, size_t subject_len,
                                size_t start_offset, size_t *out_pos,
                                size_t *out_len);

/**
 * @brief Stateful batch search that reuses VM, range_meta, and (for
 *        automaton-eligible patterns) the DFA/trie/SIMD-NFA caches across
 *        calls.
 *
 * Behaves identically to snobol_pattern_search_batch() but reuses the caches
 * already built on @p state, building them lazily on first use and reusing
 * them on every subsequent call. This avoids re-deriving metadata and
 * rebuilding the DFA per call. The stateless snobol_pattern_search_batch()
 * delegates to a temporary state internally, so both share one
 * implementation.
 *
 * @param[in,out] state  Search state created by
 *                       snobol_pattern_search_state_create().
 * @param[in]     subject Subject string (UTF-8, must outlive the call).
 * @param[in]     len     Byte length of @p subject.
 * @param[out]    out     Output struct (caller-allocated, zero-initialised).
 * @return Same tri-state contract as snobol_pattern_search_batch(): true when
 *         at least one match was found; false otherwise. On false, check
 *         out->eligible to tell zero-match (eligible == true, DONE) from
 *         ineligible (eligible == false, fall back to per-call loop).
 */
bool snobol_pattern_search_batch_ex(snobol_pattern_search_state_t *state,
                                    const char *subject, size_t len,
                                    snobol_batch_result_t *out);

/**
 * @brief Get the absolute offset where the match started within the subject.
 *
 * Returns the position of the first byte of the match in the subject
 * string (not the position within the search window). Returns 0 on
 * failure or if match is NULL.
 *
 * @param[in] match Match result from snobol_pattern_search() or
 *                  snobol_pattern_search_ex().
 * @return Byte offset of the match start in the original subject.
 */
size_t snobol_match_get_position(const snobol_match_t *match);

/**
 * @brief Get the length of the match in bytes.
 *
 * @param[in] match Match result from snobol_pattern_search() or
 *                  snobol_pattern_search_ex().
 * @return Number of bytes in the match. Returns 0 on failure or NULL.
 */
size_t snobol_match_get_length(const snobol_match_t *match);

/**
 * @brief Free a match result.
 *
 * @param[in] match Match result to free.  NULL is safe.
 */
void snobol_match_free(snobol_match_t *match);

/**
 * @brief Create a new match result object.
 *
 * Allocates and zero-initializes a snobol_match_t. The caller owns the
 * returned pointer and must free it with snobol_match_free() or reuse it
 * with snobol_pattern_search_reuse().
 *
 * @return Newly allocated match object, or NULL on allocation failure.
 */
snobol_match_t *snobol_match_create(void);

/**
 * @brief Reset a match result for reuse without freeing.
 *
 * Clears all fields and frees any allocated capture strings.
 * The match object remains allocated and ready for reuse.
 * Safe to call on a zeroed or freshly allocated match object.
 *
 * @param[in,out] match Match result to reset.  NULL is safe (no-op).
 */
void snobol_match_reset(snobol_match_t *match);

/**
 * @brief Search using a caller-allocated, reusable match object.
 *
 * Functionally equivalent to snobol_pattern_search() but uses a
 * caller-provided match object instead of allocating one per call.
 * Eliminates per-call malloc/free overhead (~30 ns).
 *
 * The caller owns the match object and must call snobol_match_reset()
 * or snobol_match_free() when done.  The match object is overwritten
 * on each call.
 *
 * @param[in]     pattern    Compiled pattern to search.
 * @param[in]     subject    Subject string (UTF-8).
 * @param[in]     len        Byte length of @p subject.
 * @param[in,out] match_out  Caller-allocated match object (reusable).
 * @return true if match succeeded, false otherwise.
 *         Results are written to *match_out.
 */
bool snobol_pattern_search_reuse(snobol_pattern_t *pattern, const char *subject,
                                 size_t len, snobol_match_t *match_out);

/* Match result access */
/**
 * @brief Return whether a match result represents a successful match.
 *
 * @param[in] match Match result from snobol_pattern_match().
 * @return true if the pattern matched; false otherwise.
 */
bool snobol_match_success(snobol_match_t *match);

/**
 * @brief Retrieve the output buffer produced by a successful match.
 *
 * The output contains any text emitted by @c OP_EMIT_LITERAL / @c
 * OP_EMIT_CAPTURE instructions during the match.
 *
 * @param[in]  match Match result from snobol_pattern_match().
 * @param[out] len   If non-NULL, set to the byte length of the returned string.
 * @return Pointer to the output string (owned by @p match, do not free),
 *         or NULL if there is no output.
 */
const char *snobol_match_get_output(snobol_match_t *match, size_t *len);

/**
 * @brief Retrieve the value of a named capture variable from a match result.
 *
 * @param[in]  match Match result from snobol_pattern_match().
 * @param[in]  name  Variable name (NUL-terminated).
 * @param[out] len   If non-NULL, set to the byte length of the returned string.
 * @return Pointer to the variable value (owned by @p match, do not free),
 *         or NULL if the variable was not set during the match.
 */
const char *snobol_match_get_variable(snobol_match_t *match, const char *name,
                                      size_t *len);

/* -----------------------------------------------------------------------
 * One-shot convenience match API
 *
 * snobol_match() bundles lex→parse→compile→VM execution into a single
 * call, freeing all intermediate resources internally.  Use this for
 * simple one-off matches; for repeated matching of the same pattern use
 * snobol_pattern_compile() + snobol_pattern_match() instead.
 * ----------------------------------------------------------------------- */

/**
 * @brief Result from the one-shot snobol_match() convenience API.
 *
 * Unlike the opaque snobol_match_t (which is used by the multi-step API),
 * this struct is non-opaque so callers can directly read the fields.
 */
typedef struct snobol_match_result {
  bool success;      /**< Whether the pattern matched */
  char *error;       /**< Malloc'd error message (NULL on success);
                          caller must free via snobol_match_result_free(). */
  char *output;      /**< Output buffer from OP_EMIT_* instructions
                          (owned, freed by snobol_match_result_free()). */
  size_t output_len; /**< Byte length of output (0 if no output). */

  /** Captured variable values (index 0 = variable "1", etc.).
   *  Each entry is a malloc'd NUL-terminated string (or NULL if not set).
   *  Freed by snobol_match_result_free(). */
  char **captures;
  size_t *capture_lens; /**< Byte lengths of each capture string. */
  int capture_count;    /**< Number of populated captures. */
} snobol_match_result_t;

/**
 * @brief One-shot convenience match: compile and run a pattern in one call.
 *
 * Bundles the full pipeline: lexer → parser → compiler → VM execution.
 * All intermediate objects are freed internally.
 *
 * @param[in]  pattern   Pattern source string (UTF-8).
 * @param[in]  pat_len   Byte length of @p pattern.
 * @param[in]  subject   Subject string (UTF-8).
 * @param[in]  sub_len   Byte length of @p subject.
 * @param[in]  flags     Bitmask of SNOBOL_FLAG_* constants (0 for default).
 * @return Newly allocated snobol_match_result_t.  Always valid; check
 *         the @c success and @c error fields.  Free with
 *         snobol_match_result_free().
 */
snobol_match_result_t *snobol_match(const char *pattern, size_t pat_len,
                                    const char *subject, size_t sub_len,
                                    uint32_t flags);

/**
 * @brief Free a snobol_match_result_t and all its owned resources.
 * @param[in] result Result to free.  NULL is safe.
 */
void snobol_match_result_free(snobol_match_result_t *result);

/* -----------------------------------------------------------------------
 * Builder API — programmatic AST construction
 *
 * Each snobol_pattern_build_*() function creates a single AST node of the
 * corresponding type.  Compound functions (concat, alt, cap, etc.) accept
 * child AST nodes and take ownership of them.  Use snobol_pattern_build_emit()
 * to finalize the root node, then snobol_pattern_build_compile() to turn it
 * into a ready-to-use pattern.
 *
 * Example (create → build → emit → compile → match):
 *   snobol_context_t *ctx = snobol_context_create();
 *   snobol_pattern_build_t *b = snobol_pattern_build_create();
 *   ast_node_t *lit = snobol_pattern_build_lit(b, "hello", 5);
 *   ast_node_t *root = snobol_pattern_build_emit(b, lit);
 *   char *err = NULL;
 *   snobol_pattern_t *pat = snobol_pattern_build_compile(ctx, root, 0, &err);
 *   // root is consumed by compile; b can be destroyed or reused.
 *   snobol_pattern_build_destroy(b);
 *   // pat is a fully initialized pattern: match, search, free.
 *   snobol_match_t *m = snobol_pattern_search(pat, "hello world", 11);
 *   snobol_pattern_free(pat);
 *   snobol_context_destroy(ctx);
 * ----------------------------------------------------------------------- */

/**
 * @brief Opaque builder state.
 */
typedef struct snobol_pattern_build snobol_pattern_build_t;

/** @brief Create a new builder. */
snobol_pattern_build_t *snobol_pattern_build_create(void);

/** @brief Destroy a builder. Does NOT free emitted AST nodes. */
void snobol_pattern_build_destroy(snobol_pattern_build_t *build);

/* --- Primitive nodes ---------------------------------------------------- */

/** @brief Create a LITERAL AST node. */
ast_node_t *snobol_pattern_build_lit(snobol_pattern_build_t *build,
                                     const char *text, size_t len);

/** @brief Create a SPAN AST node (match 1+ chars in set). */
ast_node_t *snobol_pattern_build_span(snobol_pattern_build_t *build,
                                      const char *set, size_t len);

/** @brief Create a BREAK AST node (consume until char in set). */
ast_node_t *snobol_pattern_build_brk(snobol_pattern_build_t *build,
                                     const char *set, size_t len);

/** @brief Create an ANY AST node (match single char in optional set). */
ast_node_t *snobol_pattern_build_any(snobol_pattern_build_t *build,
                                     const char *set, size_t len);

/** @brief Create a NOTANY AST node (match single char NOT in set). */
ast_node_t *snobol_pattern_build_notany(snobol_pattern_build_t *build,
                                        const char *set, size_t len);

/** @brief Create a LEN AST node (match exactly N codepoints). */
ast_node_t *snobol_pattern_build_len(snobol_pattern_build_t *build, int32_t n);

/** @brief Create an ARBNO AST node (zero or more repetitions). */
ast_node_t *snobol_pattern_build_arbno(snobol_pattern_build_t *build,
                                       ast_node_t *sub);

/* --- Capture / assignment ---------------------------------------------- */

/** @brief Create a CAP AST node (capture sub-pattern into register). */
ast_node_t *snobol_pattern_build_cap(snobol_pattern_build_t *build, int reg,
                                     ast_node_t *sub);

/** @brief Create a match-naming node: bind sub-pattern's match to register.
 *
 * Source-equivalent of `P . @vN` / `P $ vN`: compiles to the same
 * CAP_START/CAP_END bytecode as snobol_pattern_build_cap. */
ast_node_t *snobol_pattern_build_name(snobol_pattern_build_t *build, int reg,
                                      ast_node_t *sub);

/** @brief Create an ASSIGN AST node (assign register to variable). */
ast_node_t *snobol_pattern_build_assign(snobol_pattern_build_t *build, int var,
                                        int reg);

/* --- Compound nodes ---------------------------------------------------- */

/** @brief Create a CONCAT AST node (sequence of parts).  Takes ownership
 *         of @p parts array and all child nodes. */
ast_node_t *snobol_pattern_build_concat(snobol_pattern_build_t *build,
                                        ast_node_t **parts, size_t count);

/** @brief Create an ALT AST node (alternation). */
ast_node_t *snobol_pattern_build_alt(snobol_pattern_build_t *build,
                                     ast_node_t *left, ast_node_t *right);

/* --- Control flow ------------------------------------------------------ */

/** @brief Create a LABEL AST node. */
ast_node_t *snobol_pattern_build_label(snobol_pattern_build_t *build,
                                       const char *name, ast_node_t *target);

/** @brief Create a GOTO AST node. */
ast_node_t *snobol_pattern_build_goto(snobol_pattern_build_t *build,
                                      const char *label);

/* --- Position primitives ----------------------------------------------- */

/** @brief Create a POS AST node. */
ast_node_t *snobol_pattern_build_pos(snobol_pattern_build_t *build, int32_t n);

/** @brief Create a TAB AST node. */
ast_node_t *snobol_pattern_build_tab(snobol_pattern_build_t *build, int32_t n);

/** @brief Create a RPOS AST node. */
ast_node_t *snobol_pattern_build_rpos(snobol_pattern_build_t *build, int32_t n);

/** @brief Create a RTAB AST node. */
ast_node_t *snobol_pattern_build_rtab(snobol_pattern_build_t *build, int32_t n);

/** @brief Create a BREAKX AST node. */
ast_node_t *snobol_pattern_build_breakx(snobol_pattern_build_t *build,
                                        const char *set, size_t len);

/** @brief Create a BAL AST node. */
ast_node_t *snobol_pattern_build_bal(snobol_pattern_build_t *build,
                                     uint32_t open_cp, uint32_t close_cp);

/** @brief Create a FENCE AST node. */
ast_node_t *snobol_pattern_build_fence(snobol_pattern_build_t *build);

/** @brief Create a REM AST node. */
ast_node_t *snobol_pattern_build_rem(snobol_pattern_build_t *build);

/** @brief Create an ABORT AST node. */
ast_node_t *snobol_pattern_build_abort(snobol_pattern_build_t *build);

/** @brief Create a FAIL AST node. */
ast_node_t *snobol_pattern_build_fail(snobol_pattern_build_t *build);

/** @brief Create a SUCCEED AST node. */
ast_node_t *snobol_pattern_build_succeed(snobol_pattern_build_t *build);

/**
 * @brief Finalize and emit an AST tree built with the builder.
 *
 * Takes ownership of @p root and returns it.  After this call the builder
 * may be reused to build a new tree, or destroyed.  The returned node
 * must eventually be freed via snobol_ast_free().
 *
 * @param[in] build Builder instance (may be NULL for stateless usage).
 * @param[in] root  Root AST node to emit (ownership transferred).
 * @return @p root (non-NULL if input non-NULL).
 */
ast_node_t *snobol_pattern_build_emit(snobol_pattern_build_t *build,
                                      ast_node_t *root);

/**
 * @brief Compile a built AST root into a compiled pattern object.
 *
 * Runs the same post-AST pipeline as snobol_pattern_compile_ex() — bytecode
 * generation, search metadata derivation, and range metadata construction —
 * so builder-composed patterns are fully initialized and match identically
 * to their source-compiled equivalents.  No internal struct fields are
 * exposed or hand-populated by the caller.
 *
 * @param[in]  ctx    Context that will own the returned pattern.
 * @param[in]  root   Root AST node from snobol_pattern_build_emit().
 *                    Ownership is transferred: the tree is freed by this
 *                    call on both success and failure, and must NOT be
 *                    freed by the caller afterwards.
 * @param[in]  flags  Bitmask of SNOBOL_FLAG_* constants (unknown bits are
 *                    ignored).
 * @param[out] error  On failure, *error is set to a malloc'd error string
 *                    that the caller must free.  Set to NULL on success.
 * @return Compiled pattern owned by @p ctx, or NULL on compile error.
 *         Free with snobol_pattern_free() before destroying the context.
 */
snobol_pattern_t *snobol_pattern_build_compile(snobol_context_t *ctx,
                                               ast_node_t *root, uint32_t flags,
                                               char **error);

#ifdef __cplusplus
}
#endif
